## events name definition for wyscout data


## CONSTANTS
VICTORY = 1
DEFEAT = 2
DRAW = 0
DRAW_DEFEAT = 0
VICTORY_DRAW = 1

## CONSTANTS IDENTIFYING MACRO EVENTS
DUEL = 1
FOUL = 2
FREE_KICK = 3
GOALKEEPER_LEAVING_LINE = 4
INTERRUPTION = 5
OFFSIDE = 6
OTHERS = 7
PASS = 8
SAVE = 9
SHOT = 10

macroevent2name = {DUEL: 'duel', FOUL: 'foul', FREE_KICK: 'free kick', 
             GOALKEEPER_LEAVING_LINE: 'goalkeeper leaving line', 
             INTERRUPTION: 'interruption', 
             OFFSIDE: 'offside', OTHERS: 'others on the ball', 
             PASS: 'pass', SAVE: 'save attempt', SHOT: 'shot'}

macroevent2positions_index = {DUEL: 0, FOUL: 0, FREE_KICK: 0,
                              GOALKEEPER_LEAVING_LINE: 0, INTERRUPTION: 0,
                              OFFSIDE: 0, OTHERS: 0, PASS: 0, SAVE: 1, SHOT: 0
}

## CONSTANTS IDENTIFYING SUB EVENTS
# duels
AIR_DUEL = 10
GROUND_ATTACKING_DUEL = 11
GROUND_DEFENDING_DUEL = 12
GROUND_LOOSE_BALL_DUEL = 13

# fouls
NORMAL_FOUL = 20
HAND_FOUL = 21
LATE_CARD_FOUL = 22
OUT_OF_GAME_FOUL = 23
PROTEST_FOUL = 24
SIMULATION_FOUL = 25
TIME_LOST_FOUL = 26
VIOLENT_FOUL = 27

#free kicks
CORNER_FREE_KICK = 30
NORMAL_FREE_KICK = 31
CROSS_FREE_KICK = 32
SHOT_FREE_KICK = 33
GOAL_FREE_KICK = 34
PENALTY_FREE_KICK = 35
THROW_IN_FREE_KICK = 36
# goalkeeping leaving line
GOALKEEPING_LEAVING_LINE = 40
# interruption
BALL_OUT_INTERRUPTION = 50
WHISTLE_INTERRUPTION = 51
# offside
NORMAL_OFFSIDE=60
# others on the ball
ACCELERATION_OTHERS = 70
CLEARANCE_OTHERS = 71
TOUCH_OTHERS = 72
# pass
CROSS_PASS = 80
HAND_PASS = 81
HEAD_PASS = 82
HIGH_PASS = 83
LAUNCH_PASS = 84
SIMPLE_PASS = 85
SMART_PASS = 86
# save
REFLEXES_SAVE = 90
NORMAL_SAVE = 91
# shot
NORMAL_SHOT = 100

macroevent2subevents = {DUEL: [AIR_DUEL, GROUND_ATTACKING_DUEL, GROUND_DEFENDING_DUEL, GROUND_LOOSE_BALL_DUEL],
                       FOUL: [NORMAL_FOUL, HAND_FOUL, LATE_CARD_FOUL, OUT_OF_GAME_FOUL, PROTEST_FOUL, SIMULATION_FOUL,
                              TIME_LOST_FOUL, VIOLENT_FOUL],
                       FREE_KICK: [CORNER_FREE_KICK, NORMAL_FREE_KICK, CROSS_FREE_KICK, SHOT_FREE_KICK, GOAL_FREE_KICK, 
                                   PENALTY_FREE_KICK, THROW_IN_FREE_KICK],
                       INTERRUPTION: [BALL_OUT_INTERRUPTION, WHISTLE_INTERRUPTION], 
                       OFFSIDE: [NORMAL_OFFSIDE],
                       OTHERS: [ACCELERATION_OTHERS, CLEARANCE_OTHERS, TOUCH_OTHERS],
                        PASS: [CROSS_PASS, HAND_PASS, HEAD_PASS, HIGH_PASS, LAUNCH_PASS, SIMPLE_PASS, SMART_PASS],
                        SAVE: [REFLEXES_SAVE, NORMAL_SAVE],
                        SHOT: [NORMAL_SHOT]
                       }

subevents2name = {
    
    AIR_DUEL:'air duel', GROUND_ATTACKING_DUEL:'ground attacking duel', 
    GROUND_DEFENDING_DUEL:'ground defending duel', GROUND_LOOSE_BALL_DUEL:'ground loose ball duel',
                  
    NORMAL_FOUL:'normal foul', HAND_FOUL:'hand foul', LATE_CARD_FOUL:'late card foul', 
    OUT_OF_GAME_FOUL:'out of game foul', PROTEST_FOUL:'protest foul', SIMULATION_FOUL:'simulation foul',
    TIME_LOST_FOUL:'time lost foul', OUT_OF_GAME_FOUL:'out of game foul', PROTEST_FOUL:'protest foul',
    SIMULATION_FOUL:'simulation foul', TIME_LOST_FOUL:'time lost foul', VIOLENT_FOUL:'violent foul',
                  
    CORNER_FREE_KICK:'corner free kick', NORMAL_FREE_KICK:'normal free kick', CROSS_FREE_KICK:'cross free kick',
    SHOT_FREE_KICK:'shot free kick', GOAL_FREE_KICK:'goal free kick', PENALTY_FREE_KICK:'penalty free kick',
    THROW_IN_FREE_KICK:'throw in free kick',
                  
    BALL_OUT_INTERRUPTION:'ball out interruption', WHISTLE_INTERRUPTION:'whistle interruption',
                  
    ACCELERATION_OTHERS:'accelleration', CLEARANCE_OTHERS:'clearance', TOUCH_OTHERS:'touch',
                  
    CROSS_PASS:'cross pass', HAND_PASS:'hand pass', HEAD_PASS:'head pass', HIGH_PASS:'high pass',
    LAUNCH_PASS:'launch pass', SIMPLE_PASS:'simple pass', SMART_PASS:'smart pass',
                  
    REFLEXES_SAVE:'reflexes save', NORMAL_SAVE:'normal save', 
                 
    NORMAL_SHOT: 'shot', 
                 
    NORMAL_OFFSIDE: 'offside', 
                 
    GOALKEEPING_LEAVING_LINE: 'goalkeeping leaving line'
}


## CONSTANTS FOR TAGS
GOAL_TAG = 101
OWN_GOAL_TAG = 102
ASSIST_TAG = 301
KEY_PASS_TAG = 302
COUNTER_ATTACK_TAG = 1901
LEFT_FOOT_TAG = 401
RIGHT_FOOT_TAG = 402
HEAD_BODY_TAG = 403
DIRECT_TAG = 1101
INDIRECT_TAG = 1102
DANGEROUS_BALL_LOST_TAG = 2001
BLOCKED_TAG = 2101
HIGH_TAG = 801
LOW_TAG = 802
INTERCEPTION_TAG = 1401
CLEARANCE_TAG = 1501
OPPORTUNITY_TAG = 201
FEINT_TAG = 1301
MISSED_BALL_TAG = 1302
FREE_SPACE_RIGHT_TAG = 501
FREE_SPACE_LEFT_TAG = 502
TAKE_ON_LEFT_TAG = 503
TAKE_ON_RIGHT_TAG = 504
SLIDING_TACKLE_TAG = 1601
ANTICIPATED_TAG = 601
ANTICIPATION_TAG = 602
RED_CARD_TAG = 1701
YELLOW_CARD_TAG = 1702
SECOND_YELLOW_CARD_TAG = 1703
THROUGH_TAG = 901
FAIRPLAY_TAG = 1001
LOST_TAG = 701
NEUTRAL_TAG = 702
WON_TAG = 703
ACCURATE_TAG = 1801
NOT_ACCURATE_TAG = 1802
NO_TAG = -1
tag2name = {
    GOAL_TAG: 'GOAL', OWN_GOAL_TAG: 'OWN GOAL', ASSIST_TAG: 'assist', KEY_PASS_TAG:'key pass', 
    COUNTER_ATTACK_TAG:'counter attack', LEFT_FOOT_TAG:'left foot', RIGHT_FOOT_TAG:'right foot', 
    HEAD_BODY_TAG:'head_body', DIRECT_TAG:'direct', INDIRECT_TAG:'indirect', 
    DANGEROUS_BALL_LOST_TAG:'dangerous ball lost', BLOCKED_TAG:'blocked', HIGH_TAG:'high', 
    LOW_TAG:'low', INTERCEPTION_TAG: 'interception', CLEARANCE_TAG:'clearance', OPPORTUNITY_TAG:'opportunity', 
    FEINT_TAG:'feint', MISSED_BALL_TAG:'missed ball', FREE_SPACE_RIGHT_TAG:'free space right', 
    FREE_SPACE_LEFT_TAG:'free space left', TAKE_ON_LEFT_TAG:'takeon left', TAKE_ON_RIGHT_TAG:'takeon right', 
    SLIDING_TACKLE_TAG:'sliding tackle', ANTICIPATED_TAG:'anticipated', ANTICIPATION_TAG:'anticipation',
    RED_CARD_TAG:'red card', YELLOW_CARD_TAG: 'yellow card', SECOND_YELLOW_CARD_TAG: 'second yellow card',
    THROUGH_TAG:'through', FAIRPLAY_TAG:'fairplay', LOST_TAG:'lost', NEUTRAL_TAG:'neutral', 
    WON_TAG:'won', ACCURATE_TAG:'accurate', NOT_ACCURATE_TAG:'not accurate', NO_TAG: 'no tag'
}


subevent2tags = {
    
    ## OFFSIDE
    NORMAL_OFFSIDE: [],
    
    ## LEAVING LINE
    GOALKEEPING_LEAVING_LINE: [],
    
    ## SHOT
    NORMAL_SHOT: 
    [LEFT_FOOT_TAG, OPPORTUNITY_TAG, NOT_ACCURATE_TAG, ACCURATE_TAG, HEAD_BODY_TAG, RIGHT_FOOT_TAG, BLOCKED_TAG, GOAL_TAG, INTERCEPTION_TAG, COUNTER_ATTACK_TAG, ASSIST_TAG], 

##### DUELS ########
    
GROUND_ATTACKING_DUEL:
    [LOST_TAG, NOT_ACCURATE_TAG, WON_TAG, ACCURATE_TAG, TAKE_ON_RIGHT_TAG, ANTICIPATION_TAG, FREE_SPACE_LEFT_TAG, TAKE_ON_LEFT_TAG, NEUTRAL_TAG, FREE_SPACE_RIGHT_TAG, DANGEROUS_BALL_LOST_TAG, INTERCEPTION_TAG, COUNTER_ATTACK_TAG, SLIDING_TACKLE_TAG, OPPORTUNITY_TAG], 
    
AIR_DUEL: 
    [LOST_TAG, NOT_ACCURATE_TAG, WON_TAG, ACCURATE_TAG, NEUTRAL_TAG, COUNTER_ATTACK_TAG, KEY_PASS_TAG, ASSIST_TAG], 
        
GROUND_LOOSE_BALL_DUEL: 
    [LOST_TAG, NOT_ACCURATE_TAG, WON_TAG, ACCURATE_TAG, NEUTRAL_TAG, SLIDING_TACKLE_TAG, COUNTER_ATTACK_TAG, INTERCEPTION_TAG, DANGEROUS_BALL_LOST_TAG], 
    
    GROUND_DEFENDING_DUEL: [SLIDING_TACKLE_TAG, WON_TAG, ACCURATE_TAG, LOST_TAG, NOT_ACCURATE_TAG, TAKE_ON_LEFT_TAG, ANTICIPATED_TAG, FREE_SPACE_RIGHT_TAG, TAKE_ON_RIGHT_TAG, NEUTRAL_TAG, FREE_SPACE_LEFT_TAG, COUNTER_ATTACK_TAG], 
  
######### FREE KICKS ###########
    
SHOT_FREE_KICK: 
    [RIGHT_FOOT_TAG, DIRECT_TAG, OPPORTUNITY_TAG, ACCURATE_TAG, BLOCKED_TAG, NOT_ACCURATE_TAG, LEFT_FOOT_TAG, INDIRECT_TAG, GOAL_TAG], 
    
CROSS_FREE_KICK: 
    [HIGH_TAG, NOT_ACCURATE_TAG, ASSIST_TAG, ACCURATE_TAG, KEY_PASS_TAG], 
    
NORMAL_FREE_KICK: 
    [ACCURATE_TAG, NOT_ACCURATE_TAG, KEY_PASS_TAG], 
    
CORNER_FREE_KICK: 
    [HIGH_TAG, NOT_ACCURATE_TAG, ACCURATE_TAG, KEY_PASS_TAG, OPPORTUNITY_TAG, ASSIST_TAG], 
    
THROW_IN_FREE_KICK: 
    [ACCURATE_TAG, NOT_ACCURATE_TAG, FAIRPLAY_TAG], 
    
PENALTY_FREE_KICK: 
    [GOAL_TAG, RIGHT_FOOT_TAG, ACCURATE_TAG, LEFT_FOOT_TAG, NOT_ACCURATE_TAG], 
    
GOAL_FREE_KICK: [NO_TAG], 
    
    
 #### FOULS ####
    
PROTEST_FOUL: 
    [YELLOW_CARD_TAG, RED_CARD_TAG, SECOND_YELLOW_CARD_TAG], 
    
SIMULATION_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
TIME_LOST_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
VIOLENT_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
NORMAL_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
HAND_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
LATE_CARD_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
OUT_OF_GAME_FOUL: 
    [YELLOW_CARD_TAG, SECOND_YELLOW_CARD_TAG, RED_CARD_TAG], 
    
#WHISTLE_INTERRUPTION: [], 
    
#BALL_OUT_INTERRUPTION: [], 
    
 ### TOUCHS ####
    
TOUCH_OTHERS: 
    [INTERCEPTION_TAG, MISSED_BALL_TAG, OPPORTUNITY_TAG, COUNTER_ATTACK_TAG, FEINT_TAG, DANGEROUS_BALL_LOST_TAG, ASSIST_TAG, OWN_GOAL_TAG], 
    
CLEARANCE_OTHERS: 
    [INTERCEPTION_TAG, NOT_ACCURATE_TAG, ACCURATE_TAG, COUNTER_ATTACK_TAG, FAIRPLAY_TAG, MISSED_BALL_TAG, OWN_GOAL_TAG], 
    
ACCELERATION_OTHERS: 
    [NOT_ACCURATE_TAG, ACCURATE_TAG, COUNTER_ATTACK_TAG, INTERCEPTION_TAG], 
    
##### SAVES ####   
    
NORMAL_SAVE: 
    [ACCURATE_TAG, GOAL_TAG, NOT_ACCURATE_TAG, COUNTER_ATTACK_TAG], 
    
REFLEXES_SAVE: 
    [ACCURATE_TAG, GOAL_TAG, NOT_ACCURATE_TAG, COUNTER_ATTACK_TAG], 
  
    
####  PASSES  #####################
    
HEAD_PASS: 
    [INTERCEPTION_TAG, ACCURATE_TAG, NOT_ACCURATE_TAG, ASSIST_TAG, COUNTER_ATTACK_TAG, KEY_PASS_TAG, DANGEROUS_BALL_LOST_TAG], 
    
HIGH_PASS: 
    [NOT_ACCURATE_TAG, ACCURATE_TAG, KEY_PASS_TAG, THROUGH_TAG, COUNTER_ATTACK_TAG, INTERCEPTION_TAG, ASSIST_TAG], 
    
CROSS_PASS: 
    [LEFT_FOOT_TAG, HIGH_TAG, NOT_ACCURATE_TAG, RIGHT_FOOT_TAG, ACCURATE_TAG, KEY_PASS_TAG, ASSIST_TAG, BLOCKED_TAG, COUNTER_ATTACK_TAG, INTERCEPTION_TAG], 
    
HAND_PASS: 
    [ACCURATE_TAG, NOT_ACCURATE_TAG, INTERCEPTION_TAG, COUNTER_ATTACK_TAG, FAIRPLAY_TAG], 
    
SMART_PASS: 
    [NOT_ACCURATE_TAG, ACCURATE_TAG, THROUGH_TAG, KEY_PASS_TAG, ASSIST_TAG, COUNTER_ATTACK_TAG, INTERCEPTION_TAG],
    
LAUNCH_PASS: 
    [ACCURATE_TAG, NOT_ACCURATE_TAG, INTERCEPTION_TAG, FAIRPLAY_TAG, DANGEROUS_BALL_LOST_TAG], 
    
SIMPLE_PASS: [ACCURATE_TAG, NOT_ACCURATE_TAG, INTERCEPTION_TAG, COUNTER_ATTACK_TAG, KEY_PASS_TAG, FAIRPLAY_TAG, DANGEROUS_BALL_LOST_TAG, ASSIST_TAG, OWN_GOAL_TAG]
    
}

#subevent2outcome={PROTEST_FOUL: 
#    subevent2tags[PROTEST_FOUL]+ [NO_TAG],
    
#SIMULATION_FOUL: 
#    subevent2tags[SIMULATION_FOUL]+[ NO_TAG], 
    
#TIME_LOST_FOUL: 
#    subevent2tags[TIME_LOST_FOUL]+[NO_TAG], 
    
#VIOLENT_FOUL: 
#    subevent2tags[VIOLENT_FOUL]+[NO_TAG],
    
#NORMAL_FOUL: 
#    subevent2tags[NORMAL_FOUL]+[NO_TAG],
    
#HAND_FOUL: 
#    subevent2tags[HAND_FOUL]+[NO_TAG ], 
    
#LATE_CARD_FOUL: 
#    subevent2tags[LATE_CARD_FOUL]+[ NO_TAG], 
    
#OUT_OF_GAME_FOUL: 
#    subevent2tags[OUT_OF_GAME_FOUL]+[NO_TAG],
#  'default':[ACCURATE_TAG, NOT_ACCURATE_TAG],
#  TOUCH_OTHERS:subevent2tags[TOUCH_OTHERS],
#}




